AllCops:
  TargetRubyVersion: 2.4.1

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
  Exclude:
    - "app/controllers/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Max: 120

ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Style/RaiseArgs:
  EnforcedStyle: compact
